Document: saltmaster-layout
Title: Debian saltmaster-layout Manual
Author: <insert document author here>
Abstract: This manual describes what saltmaster-layout is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/saltmaster-layout/saltmaster-layout.sgml.gz

Format: postscript
Files: /usr/share/doc/saltmaster-layout/saltmaster-layout.ps.gz

Format: text
Files: /usr/share/doc/saltmaster-layout/saltmaster-layout.text.gz

Format: HTML
Index: /usr/share/doc/saltmaster-layout/html/index.html
Files: /usr/share/doc/saltmaster-layout/html/*.html
